
server:
  port: 8000

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: dafaultgateway
  cloud:
    gateway:
      globalcore:
        cors-configurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders: "*"
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: hello-world
            preLogger: false
            postLogger: true
      routes:
        - id: userServiceLogin
          uri: lb://USERSERVICE
          predicates:
            - Path=/user/login
            - Method=POST
          filters:
            - CustomFilter
        - id: userServiceMe
          uri: lb://USERSERVICE
          predicates:
            - Path=/user/me
            - Method=GET
          filters:
            - CustomFilter
        - id: cafeServiceMy
          uri: lb://CAFESERVICE
          predicates:
            - Path=/cafe/my
            - Method=GET
        # 카테고리 전체 조회
        - id: categoryService
          uri: lb://CATEGORYSERVICE
          predicates:
            - Path=/category
            - Method=GET
        # 특정 카테고리 조회(Id 사용)
        - id: categoryServiceR
          uri: lb://CATEGORYSERVICE
          predicates:
            - Path=/category/**
            - Method=GET
        # 카테고리 삭제(Id 사용)
        - id: categoryServiceD
          uri: lb://CATEGORYSERVICE
          predicates:
            - Path=/category/**
            - Method=DELETE
        # 카테고리 등록
        - id: categoryServiceC
          uri: lb://CATEGORYSERVICE
          predicates:
            - Path=/category
            - Method=POST
        # 카테고리 수정
        - id: categoryServiceU
          uri: lb://CATEGORYSERVICE
          predicates:
            - Path=/category/**
            - Method=PUT
        # 댓글 수정
        - id: commentServiceU
          uri: lb://COMMENTSERVICE
          predicates:
            - Path=/comment/**
            - Method=PUT
        # 댓글 삭제
        - id: commentServiceD
          uri: lb://COMMENTSERVICE
          predicates:
            - Path=/comment/**
            - Method=DELETE
        # 댓글 추가
        - id: commentServiceC
          uri: lb://COMMENTSERVICE
          predicates:
            - Path=/comment
            - Method=POST
        # 댓글 조회
        - id: commentServiceR
          uri: lb://COMMENTSERVICE
          predicates:
            - Path=/comment/**
            - Method=GET



#   Netty started on port 8000
#  Netty ? ????
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace
token:
  secret: user_token

jwt:
  secret_key: asdfghjkl
  expTime: 864000000